start :- 
	write(' ____  _____  _  _  ____  __  __  _____  _  _ '),nl,
	write('(_  _)(  _  )( )/ )( ___)(  \\/  )(  _  )( \\( ) '), nl,
	write('  )(   )(_)(  )  (  )__)  )    (  )(_)(  )  ( '), nl,
	write(' (__) (_____)(_)\\_)(____)(_/\\/\\_)(_____)(_)\\_)'),nl,
	write(' ____  ____  _____     _     __    _____  ___'),nl,
	write('(  _ \\(  _ \\(  _  )   ( )   (  )  (  _  )/ __) '),nl,
	write(' )___/ )   / )(_)(    /_\\/   )(__  )(_)(( (_-.'),nl,
	write('(__)  (_)\\_)(_____)  (__/\\  (____)(_____)\\___/ '),nl,
	nl,
	write('Gotta catch them all!'),nl,
	nl,
	write('Hello there! Welcome to the world of Tokemon! My name is Aril! People call me the Tokemon Professor! This world is inhabited by creatures called Tokemon! There are hundreds of Tokemon loose in Labtek 5! You can catch them all to get stronger, but what I am really interested in are the 2 legendary Tokemons, Icanmon dan Sangemon. If you can defeat or capture all those Tokemons I will not kill you.'),nl,
	nl,
	write('Available commands: '), nl,
	write(' start. --start the game!'), nl,
	write(' help. --show available commands'), nl,
	write(' quit. --quit the game'), nl,
	write(' n. s. e. w. --move'), nl,
	write(' map. --look at the map'), nl,
	write(' heal --cure Tokemon in inventory if in gym center'), nl,
	write(' status. --show your status'), nl,
	write(' save(Filename). --save your game'), nl,
	write(' load(Filename). --load previously saved game'), nl,
	nl,
	write('Legends: '),nl,
	write(' -X = Pagar'),nl,
	write(' -P = Player'),nl,
	write(' -G = Gym'),nl.
help :-
	write('Available commands: '), nl,
	write(' start. --start the game!'), nl,
	write(' help. --show available commands'), nl,
	write(' quit. --quit the game'), nl,
	write(' w. a. s. d. --move'), nl,
	write(' map. --look at the map'), nl,
	write(' heal --cure Tokemon in inventory if in gym center'), nl,
	write(' status. --show your status'), nl,
	write(' save(Filename). --save your game'), nl,
	write(' load(Filename). --load previously saved game'), nl,
	nl,
	write('Legends: '),nl,
	write(' -X = Pagar'),nl,
	write(' -P = Player'),nl,
	write(' -G = Gym'),nl.
